name: Build Linux Container Image and Push to ACR
env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  REPO_NAME: ${{ github.event.repository.name }}
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: $ACR_NAME
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t $ACR_NAME/$REPO_NAME:${{ github.sha }}
        docker push $ACR_NAME/$REPO_NAME:${{ github.sha }}
