name: Deploy and Run
env:
  REPO_NAME: ${{ github.event.repository.name }}
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
    - name: 'Login via Docker'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR_NAME }}/$REPO_NAME:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}/$REPO_NAME:${{ github.sha }}
    
    - name: 'deploy Container App'
      uses: azure/aci-deploy@v1
      with:
        location: eastus
        name: mycontainer
        resource-group: umGroupResource
        image: ${{ secrets.ACR_NAME }}/$REPO_NAME:${{ github.sha }}
        dns-name-label: flask-4-estructura
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        ports: 80
        cpu: 1
        memory: 1
    - name: 'logout'
      run: |
        az logout
